### ISSUE TITLE
Remove the DM thing

### ISSUE THREAD

**Issue by yeSpud** [uaf-cs/nookbot#1]
every time a user joins the server, nookbot DMs them with information that is already available in the server rules channel.

So if a user joins multiple times they get an ever increasing wall of shit from nookbot
![Capture](https://user-images.githubusercontent.com/10385195/74208930-1acdeb80-4c32-11ea-9444-8ca1328be2d5.PNG)

**Comment by yeSpud** [comment]
Im up to 13 so far

**Comment by Arsh25** [comment]
@yeSpud thanks for the concern. We have noticed that a DM helps users who are new to discord understand our server requirements. We have seen multiple cases where the verification process has gone smoothly due to the bot DM'ing the user and walking them through the process. 

This is a useful feature and the bot only messages a new user when they join the server. Based on data, we have not had too many users leave and rejoin the server multiple times so they do not get multiple messages from the bot
